version: 2
updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      target-branch: 'develop'
      labels:
          - 'gh actions dependencies'

    # Maintain dependencies for yarn
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      target-branch: 'develop'
      open-pull-requests-limit: 15
      labels:
          - 'npm dependencies'
      groups:
          angular-cli/devkit:
              patterns:
                  - '@angular/cli'
                  - '@angular-devkit/*'
          angular:
              patterns:
                  - '@angular/*'
              exclude-patterns:
                  - '@angular/cli'
                  - '@angular/cdk'
                  - '@angular/material'
          angular-material:
              patterns:
                  - '@angular/cdk'
                  - '@angular/material'
          angular-eslint:
              patterns:
                  - '@angular-eslint/*'
          typescript-eslint:
              patterns:
                  - '@typescript-eslint/*'
