name: CI Workflow
on:
    push:
        # trigger on all branches except for dependabot-triggered push events
        branches-ignore: [dependabot/**]
        tags:
            - 'v*' # trigger on all tags
        paths-ignore:
            - '**.md' # ignore changes in markdown files
    pull_request:
        branches: [develop]
        types: [opened, synchronize, reopened]

# globals
env:
    # general settings
    MAIN_REPO_OWNER: musicEnfanthen # Main repo owner (default: webern-unibas-ch; should not be changed)

jobs:
    test:
        name: Run tests (Node v${{ matrix.node-version }}, ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18.13, 20.9]
        steps:
            - name: Checkout repo
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v3
              with:
                  fetch-depth: 0 # Get all history and branches
            - name: Set up node ${{ matrix.node-version}}
              uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # ratchet:actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - name: yarn install dependencies
              run: |
                  yarn install
            - name: Run CI tests with coverage
              run: |
                  yarn run test:ci
            - name: Test build for GH Pages
              run: |
                  yarn run build:gh

    deploy:
        name: Deploy app from main (Node v${{ matrix.node-version }}, ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        needs: test
        # run only on main
        if: github.ref == 'refs/heads/main'
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [20.9]
        steps:
            - name: Checkout repo
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v3
            - name: Set up node ${{ matrix.node-version}}
              uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # ratchet:actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - name: yarn install dependencies
              run: |
                  yarn install
            - name: Build app for GH Pages
              run: |
                  yarn run build:gh
            - name: Create default index.html for locales
              run: |
                  cp locale-base.html dist/awg-website/index.html
            - name: Deploy to GH Pages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn run deploy:ci

    release:
        name: Create Release from tag
        runs-on: ${{ matrix.os }}
        needs: test
        # run only on tags
        if: startsWith(github.ref, 'refs/tags/')
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [20.9]
        steps:
            - name: Get tag version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
            - name: Create Release
              id: create_release
              if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
              uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # ratchet:softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAG_VERSION: ${{ steps.get_version.outputs.VERSION }}
              with:
                  name: Release ${{ env.TAG_VERSION }}
                  body: "Website of the [Anton Webern Gesamtausgabe](https://www.anton-webern.ch), located at the Department of Musicology of the University of Basel. It is written in [Angular](https://angular.io/) and runs on [www.anton-webern.ch](https://www.anton-webern.ch).\n\n Changes since last release: https://github.com/${{ github.repository }}/blob/${{ env.TAG_VERSION }}/CHANGELOG.md"
                  draft: false
                  prerelease: false
